### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by TobiasDeBruijn** [Dusk-Labs/dim#442]
Hey there,

First of all thanks for all the amazing work.

It's been a while since the latest GitHub release. v0.3.0-rc6 being released in October of last year. How far along is dim on the road to an `rc7`, or a 0.3.1 for example?

The `dev` tag for Docker is updated regularly, might it be a good idea to publish weekly, or monthly tags as well, or when a certain milestone is hit?

Thanks!

**Comment by vgarleanu** [comment]
Hi. the last release was indeed quite a long time ago. Progress has decreased a bit since last year due to lack of manpower and developers. I hope to release a new candidate (0.4-rc1) once #420 gets merged in (and hopefully #439) tho.

In general we release a new version once a project board is emptied. Currently the project board we are tracking is https://github.com/Dusk-Labs/dim/projects/4

#420 Is a major feature we want to introduce, and once we clear up the project board above (which is mostly made up of bugfixes and UX improvements) 0.4 will come out.

**Comment by TobiasDeBruijn** [comment]
Sounds good!

In the meantime I'll be working with the source then. Building was successful, however I'm running into some issues migrating the database from rc6. I'm not familiar with the sqlite3 library in Rust, only using mysql usually, so I'm unsure how to solve the issue:
```
May 14 15:59:44 dim-media dim[37462]: [database/src/lib.rs:85] err = VersionMismatch(
May 14 15:59:44 dim-media dim[37462]:     20210619211347,
May 14 15:59:44 dim-media dim[37462]: )
```
I'm using commit 9196a69.

**Comment by cobyge** [comment]
#437 includes fixes for the migration process, and should hopefully be merged soon.

**Comment by TobiasDeBruijn** [comment]
Check. Will wait for that then. Thanks!

**Comment by vgarleanu** [comment]
@TobiasDeBruijn The PR above has been merged, you can try spinning up the latest dev image once its up on ghcr.

**Comment by TobiasDeBruijn** [comment]
Thanks!

I imagine the same goes for compiling from source and running that? I don't use docker for Dim.

**Comment by vgarleanu** [comment]
> I imagine the same goes for compiling from source and running that? I don't use docker for Dim.

Yep. Just pull the latest master commits and cargo run.

**Comment by TobiasDeBruijn** [comment]
Awesome. Thanks!
